#!/usr/bin/env node
// Bump every workspace package.json to the same version, in lockstep. docko publishes a single
// bundled `docko-workspace` package, so all member versions must move together.
//
// Usage: node scripts/bump-version.mjs <version>
//   e.g. node scripts/bump-version.mjs 0.1.0-alpha.15

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const MANIFESTS = [
  'package.json',
  'packages/core/package.json',
  'packages/cli/package.json',
  'packages/adapters/claude-code/package.json',
  'packages/adapters/claude-code/plugin/.claude-plugin/plugin.json',
  // This repo dogfoods its own adapter: the committed install is regenerated by `install`, so it
  // must move with the release or `docko adapter claude-code doctor` reports drift here.
  '.claude-plugin/docko/plugin.json'
];

const SEMVER = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

const version = process.argv[2];
if (!version || !SEMVER.test(version)) {
  console.error(`Usage: node scripts/bump-version.mjs <version>\nGot: ${version ?? '(nothing)'}`);
  process.exit(1);
}

// The hook launcher carries its own version header so an installed copy can be compared against
// the shipped one (`docko adapter claude-code doctor`). The repo-local copy is byte-compared with
// the shipped one by the plugin tests, so both are stamped here.
const LAUNCHERS = [
  'packages/adapters/claude-code/plugin/scripts/docko-claude-hook.mjs',
  '.claude-plugin/docko/scripts/docko-claude-hook.mjs'
];

const VERSION_FIELD = /("version":\s*")[^"]+(")/;
const LAUNCHER_HEADER = /^\/\/ docko-launcher-version:.*$/m;

// Re-bumping to the version already on disk is a normal thing to do (a release retried, a
// half-applied bump finished by hand), so an unchanged file is only an error when the field the
// script is supposed to rewrite is missing altogether.
function stamp(relative, pattern, replacement) {
  const file = path.join(repoRoot, relative);
  const source = readFileSync(file, 'utf8');
  if (!pattern.test(source)) {
    console.error(`No ${pattern === VERSION_FIELD ? 'version field' : 'docko-launcher-version header'} in ${relative}`);
    process.exit(1);
  }

  const next = source.replace(pattern, replacement);
  if (next === source) {
    console.log(`${relative} already at ${version}`);
    return;
  }

  writeFileSync(file, next);
  console.log(`bumped ${relative} -> ${version}`);
}

for (const relative of MANIFESTS) {
  stamp(relative, VERSION_FIELD, `$1${version}$2`);
}

for (const relative of LAUNCHERS) {
  stamp(relative, LAUNCHER_HEADER, `// docko-launcher-version: ${version}`);
}

console.log('\nNext: pnpm install (refresh lockfile), commit, open a PR, then run the Release workflow.');
